version: '3.7'
services:
  next:
    container_name: next
    build: .
    ports:
      - '3000:3000'
    networks:
      - default
  redis:
    container_name: redis
    image: 'redis:alpine'
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - default
#  redis-commander:
#    container_name: redis-commander
#    image: rediscommander/redis-commander
#    restart: unless-stopped
#    environment:
#      - "REDIS_HOST=localhost"
#      - "REDIS_PORT=6379"
#    ports:
#      - "8081:8081"
#    depends_on:
#      - redis
#    networks:
#      - default
networks:
  default:
    driver: bridge
